---@diagnostic disable: undefined-global
---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xuan.
--- DateTime: 2026/8/1 20:40
---

if(redis.call('get', KEYS[1]) == ARGV[1]) then
    return redis.call('del', KEYS[1])
end
return 0